In [19]:
import duckdb
import pandas as pd
import os
from datetime import datetime

In [20]:
con = duckdb.connect(database='dados_duckdb.db', read_only=False)

In [27]:
arquivo = 'z0019_2.csv'
data_ingestao = datetime.now()
df = pd.read_csv(f'../landing/{arquivo}', sep=';')
df['nome_arquivo'] = arquivo
df['data_ingestao'] = data_ingestao
df.head()

   NATBR    MAKTX WERKS  MAINS  LABST nome_arquivo              data_ingestao
0  10004    SERRA  BT50    100    200  z0019_2.csv 2025-06-03 17:08:19.563897
1  10005  MACHADO  BT50    100    100  z0019_2.csv 2025-06-03 17:08:19.563897
2  10003    PREGO  BT10    100     60  z0019_2.csv 2025-06-03 17:08:19.563897

In [22]:
df.head()

   NATBR     MAKTX WERKS  MAINS  LABST nome_arquivo              data_ingestao
0  10001  PARAFUSO  BT10    100    100  z0019_1.csv 2025-06-03 17:06:38.858173
1  10002   MARTELO  BT50    100   1500  z0019_1.csv 2025-06-03 17:06:38.858173
2  10003     PREGO  BT10    100     50  z0019_1.csv 2025-06-03 17:06:38.858173

In [23]:
con.execute("""
    CREATE TABLE IF NOT EXISTS bronze_produtos (
        NATBR VARCHAR,
        MAKTX VARCHAR,
        WERKS VARCHAR,
        MAINS VARCHAR,
        LABST VARCHAR,
        nome_arquivo VARCHAR,
        data_ingestao TIMESTAMP                
    )
""")

In [28]:
con.execute("INSERT INTO bronze_produtos SELECT * FROM df")

In [30]:
resultado = con.execute("SELECT * FROM bronze_produtos").fetchdf()
resultado.head(6)

   NATBR     MAKTX WERKS MAINS LABST nome_arquivo              data_ingestao
0  10001  PARAFUSO  BT10   100   100  z0019_1.csv 2025-06-03 17:06:38.858173
1  10002   MARTELO  BT50   100  1500  z0019_1.csv 2025-06-03 17:06:38.858173
2  10003     PREGO  BT10   100    50  z0019_1.csv 2025-06-03 17:06:38.858173
3  10004     SERRA  BT50   100   200  z0019_2.csv 2025-06-03 17:08:19.563897
4  10005   MACHADO  BT50   100   100  z0019_2.csv 2025-06-03 17:08:19.563897
5  10003     PREGO  BT10   100    60  z0019_2.csv 2025-06-03 17:08:19.563897

In [31]:
con.close()